[package]
name = "dummy_c_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.2"
nom_locate = "4.0.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
anyhow = "1.0.68"
thiserror = "1.0.38"
clap = { version="4.1.3", features= ["derive"]}
